version: "3.8"

networks:
  capstone-frontend:

services:
  capstone-fe:
    image: dihson103/capstone-fe:v6.6
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    ports:
      - "3000:3000"
    networks:
      - capstone-frontend

  nginx:
    image: nginx:latest
    container_name: reverse_proxy_fe
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    depends_on:
      - capstone-fe
    networks:
      - capstone-frontend
